;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                 GENERAL.INC                                ;
;                      Include File For General Constants                    ;
;                                   EE/CS 51                                 ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains general constants used in files related to the display
; functions.
;
; Revision History:
;     10/29/15  Anshul Ramachandran      initial revision

ASCII_NULL       EQU    0        ; null ASCII character, which has value 0 in ASCII
WORD_BYTES       EQU    2        ; bytes in a word